
spring:
  application:
    name: linshen-dubbo-provider1
server:
  port: 9090
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
dubbo:
  registry:
    protocol: zookeeper
    address: 116.196.113.170:2181,116.196.113.170:2182,116.196.113.170:2183
    id: lin-registry-1
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: server
  application:
    name: linshen-dubbo-provider-name1
    id: linshen-dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.linshen.dubbo.provider.service
hello:
  service:
    version: 1.0.0